name: CI-CD Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up Python
        uses: actions/setup-python@v4.6.0 
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
      - name: Run unit tests
        run: python U1.py

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
      - name: Run integration tests
        run: python IntegrationTest.py

  system-tests:
    name: Run System Tests
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
          pip install selenium
      - name: Install browser drivers
        run: |
          if [ "${{ matrix.browser }}" == "chrome" ]; then
            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            elif [ "${{ matrix.os }}" == "windows-latest" ]; then
              Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_win32.zip -OutFile chromedriver.zip
              Expand-Archive chromedriver.zip
            fi
          elif [ "${{ matrix.browser }}" == "firefox" ]; then
            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
              sudo apt-get update
              sudo apt-get install -y firefox-geckodriver
            elif [ "${{ matrix.os }}" == "windows-latest" ]; then
              Invoke-WebRequest -Uri https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-win64.zip -OutFile geckodriver.zip
              Expand-Archive geckodriver.zip
            fi
          fi
      - name: Run system tests
        run: pytest SystemTest2.py
        env:
          BROWSER: ${{ matrix.browser }}
