name: CI-CD Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    

      - name: Set up Python
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: U1.py
